name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # REQUIRED
          user: CISSSCO
          config_timezone: Asia/Kolkata

          # IMPORTANT: branch & output
          output_action: commit
          output_branch: master
          output_filename: metrics.svg

          # BASE
          template: classic
          base: header, activity, community, repositories, metadata

          # PLUGINS
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_streak: yes
          plugin_topics: yes
          plugin_projects: yes

          # THEME
          theme: dark
