name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: CISSSCO

          # Commit settings
          output_action: commit
          committer_branch: master
          filename: github-metrics.svg

          # Base sections
          template: classic
          base: header, activity, community, repositories, metadata

          # Useful plugins (VALID)
          plugin_languages: yes
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_projects: yes
          plugin_topics: yes

          # Config
          config_timezone: Asia/Kolkata
